name: hidayah
description: A new Flutter project with Clean Architecture by Abdalluh Essam
# Flutter version on machine: 3.29.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  dio:
  shared_preferences:
  easy_localization:
  intl:
  get_it:
  cached_network_image:
  flutter_screenutil:
  dartz:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/lang/
